
SOURCES =  services_yacc.mly services_lex.mll protagonists_yacc.mly protagonists_lex.mll log.ml log_yacc.mly log_lex.mll logBlareYacc.mly logBlareLex.mll  kripke.ml formula.ml  formula_yacc.mly formula_lex.mll  ctl.ml main.ml
LIBS = 	nums
RESULT  = traceur
  -include OCamlMakefile

